platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

def common_pods
    pod 'AFNetworking'
    pod 'MBProgressHUD'
end

target 'LYDemo' do
    common_pods
end
